[package]
name = "rust"
version = "0.1.0"
authors = ["TiagoMSSantos <tiago_s@outlook.pt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2="0.34.1"
